version: '3.8'
services:
  db:
    image: ldmarcos/postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tech_challenge
    ports:
      - "5432:5432"
  app:
    build: .
    environment:
      NODE_ENV: development
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: tech_challenge
      DB_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db
